ALTER TABLE books ADD COLUMN project_type VARCHAR(50) DEFAULT 'book';
ALTER TABLE books ADD COLUMN hook_score INTEGER DEFAULT NULL;
ALTER TABLE books ADD COLUMN hook_feedback TEXT DEFAULT NULL;
ALTER TABLE books ADD COLUMN script_score INTEGER DEFAULT NULL;
ALTER TABLE books ADD COLUMN script_feedback TEXT DEFAULT NULL;
